# Generated by Django 2.2 on 2019-04-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TesteModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_teste', models.CharField(help_text='Nome da forma de evasão do aluno', max_length=255, verbose_name='Descrição evasão')),
            ],
        ),
    ]
