# Generated by Django 2.2 on 2019-05-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawarehouseManager', '0002_auto_20190428_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatoevasao',
            name='quantidadeEvasao',
            field=models.IntegerField(blank=True, help_text='Quantidade de evasões', null=True, verbose_name='Quantidade evasões'),
        ),
        migrations.AddField(
            model_name='fatomatricula',
            name='quantidadeMatricula',
            field=models.IntegerField(blank=True, help_text='Quantidade de matriculas', null=True, verbose_name='Quantidade Matriculas'),
        ),
    ]
