# Generated by Django 2.2.5 on 2019-11-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawarehouseManager', '0003_auto_20190531_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fatomatricula',
            old_name='coeficienteRetencao',
            new_name='coeficienteReprovacao',
        ),
        migrations.AddField(
            model_name='fatoevasao',
            name='coeficienteRetencao',
            field=models.IntegerField(blank=True, help_text='Quantidade de evasao com retencao', null=True, verbose_name='Porcentagem de evasao com retencao'),
        ),
        migrations.AddField(
            model_name='fatoevasao',
            name='semestresCursados',
            field=models.IntegerField(blank=True, help_text='Quantidade de Semestres cursados', null=True, verbose_name='Quantidade semestres cursados'),
        ),
    ]
