# Generated by Django 2.2 on 2019-11-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawarehouseManager', '0004_auto_20191124_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatomatricula',
            name='coeficienteReprovacao',
            field=models.FloatField(blank=True, help_text='Porcentagem de reprovacao', null=True, verbose_name='Porcentagem de reprovacao'),
        ),
    ]
