# Generated by Django 2.2.5 on 2019-11-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawarehouseManager', '0005_auto_20191125_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fatoevasao',
            old_name='quantidadeRetencoes',
            new_name='quantidadeReprovacoes',
        ),
        migrations.AlterField(
            model_name='fatoevasao',
            name='coeficienteRetencao',
            field=models.FloatField(blank=True, help_text='Quantidade de evasao com retencao', null=True, verbose_name='Porcentagem de evasao com retencao'),
        ),
    ]
