# Generated by Django 2.2 on 2019-04-17 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grr_aluno', models.CharField(max_length=45)),
                ('nome_aluno', models.CharField(max_length=255)),
                ('periodo_ingresso', models.DateField()),
                ('periodo_evasao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_disciplina', models.CharField(max_length=45)),
                ('descricao_disciplina', models.CharField(max_length=45)),
                ('carga_horaria', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='FormaEvasao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_evasao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FormaIngresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_ingresso', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_situacao_matricula', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_final_matricula', models.FloatField()),
                ('faltas_matricula', models.IntegerField()),
                ('periodo_matricula', models.DateField()),
                ('alunos', models.ManyToManyField(to='tccStudentRegistration.Aluno')),
                ('disciplinas', models.ManyToManyField(to='tccStudentRegistration.Disciplina')),
                ('situacao_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tccStudentRegistration.SituacaoMatricula')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.CharField(max_length=45)),
                ('descricao_curso', models.CharField(max_length=255)),
                ('disciplinas', models.ManyToManyField(to='tccStudentRegistration.Disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='forma_evasao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tccStudentRegistration.FormaEvasao'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='forma_ingresso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tccStudentRegistration.FormaIngresso'),
        ),
    ]
