# Generated by Django 2.2 on 2019-04-20 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tccStudentRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='forma_evasao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tccStudentRegistration.FormaEvasao'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_aluno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='periodo_evasao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao_curso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='descricao_disciplina',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
