# Generated by Django 2.2 on 2019-04-20 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tccStudentRegistration', '0003_auto_20190420_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tccStudentRegistration.Aluno'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tccStudentRegistration.Disciplina'),
        ),
    ]
