# Generated by Django 2.2 on 2019-04-24 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tccStudentRegistration', '0004_auto_20190420_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='forma_evasao',
            field=models.ForeignKey(blank=True, help_text='Forma de evasão do aluno do curso', null=True, on_delete=django.db.models.deletion.CASCADE, to='tccStudentRegistration.FormaEvasao', verbose_name='Forma de evasão'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='forma_ingresso',
            field=models.ForeignKey(help_text='Forma de ingresso do aluno no curso', on_delete=django.db.models.deletion.CASCADE, to='tccStudentRegistration.FormaIngresso', verbose_name='Forma de ingresso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='grr_aluno',
            field=models.CharField(help_text='GRR do aluno', max_length=45, verbose_name='GRR do aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_aluno',
            field=models.CharField(blank=True, help_text='Nome do aluno', max_length=255, null=True, verbose_name='Nome do aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='periodo_evasao',
            field=models.DateField(blank=True, help_text='Período de evasão do aluno do curso', null=True, verbose_name='Período evasão'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='periodo_ingresso',
            field=models.DateField(help_text='Período de ingresso do aluno no curso', verbose_name='Período de ingresso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo_curso',
            field=models.CharField(help_text='Carga de identificação do curso', max_length=45, verbose_name='Código do curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao_curso',
            field=models.CharField(blank=True, help_text='Nome do curso', max_length=255, null=True, verbose_name='Descrição do curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='disciplinas',
            field=models.ManyToManyField(help_text='Disciplinas relacionadas ao curso', to='tccStudentRegistration.Disciplina', verbose_name='Disciplinas'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.CharField(blank=True, help_text='Carga horária da disciplina', max_length=45, null=True, verbose_name='Carga horária da disciplina'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='codigo_disciplina',
            field=models.CharField(help_text='Código de identificação da disciplina', max_length=45, verbose_name='Código da disciplina'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='descricao_disciplina',
            field=models.CharField(blank=True, help_text='Nome da disciplina', max_length=45, null=True, verbose_name='Descrição da disciplina'),
        ),
        migrations.AlterField(
            model_name='formaevasao',
            name='descricao_evasao',
            field=models.CharField(help_text='Nome da forma de evasão do aluno', max_length=255, verbose_name='Descrição evasão'),
        ),
        migrations.AlterField(
            model_name='formaingresso',
            name='descricao_ingresso',
            field=models.CharField(help_text='Nome da forma de ingresso do aluno', max_length=255, verbose_name='Descrição ingresso'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(help_text='GRR e nome do aluno', on_delete=django.db.models.deletion.CASCADE, to='tccStudentRegistration.Aluno', verbose_name='Nome do aluno'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='disciplina',
            field=models.ForeignKey(help_text='Disciplina em que o aluno está matriculado', on_delete=django.db.models.deletion.CASCADE, to='tccStudentRegistration.Disciplina', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='faltas_matricula',
            field=models.IntegerField(help_text='Faltas totais na disciplina', verbose_name='Faltas da matrícula'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='media_final_matricula',
            field=models.FloatField(help_text='Média final na disciplina', verbose_name='Média final da matrícula'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='periodo_matricula',
            field=models.DateField(help_text='Período em que ocorreu a matrícula na disciplina', verbose_name='Período da matrícula'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='situacao_matricula',
            field=models.ForeignKey(help_text='Situação da matrícula do aluno na disciplina', on_delete=django.db.models.deletion.CASCADE, to='tccStudentRegistration.SituacaoMatricula', verbose_name='Situação da matrícula'),
        ),
        migrations.AlterField(
            model_name='situacaomatricula',
            name='descricao_situacao_matricula',
            field=models.CharField(help_text='Nome da situação da matrícula', max_length=100, verbose_name='Descrição da situação da matrícula'),
        ),
    ]
