# Generated by Django 2.2 on 2019-04-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tccStudentRegistration', '0007_auto_20190427_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.IntegerField(blank=True, help_text='Carga horária da disciplina', max_length=45, null=True, verbose_name='Carga horária da disciplina'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='descricao_disciplina',
            field=models.CharField(blank=True, help_text='Nome da disciplina', max_length=255, null=True, verbose_name='Descrição da disciplina'),
        ),
    ]
