# Generated by Django 2.2.5 on 2019-11-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tccStudentRegistration', '0010_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='formaevasao',
            name='cod_tabela',
            field=models.IntegerField(blank=True, help_text='Codigo na tabela do historico', null=True, verbose_name='Codigo na tabela do historico'),
        ),
    ]
