# Generated by Django 2.2.5 on 2019-11-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tccStudentRegistration', '0011_formaevasao_cod_tabela'),
    ]

    operations = [
        migrations.AddField(
            model_name='formaingresso',
            name='cod_tabela',
            field=models.IntegerField(blank=True, help_text='Codigo na tabela do historico', null=True, verbose_name='Codigo na tabela do historico'),
        ),
        migrations.AddField(
            model_name='situacaomatricula',
            name='cod_tabela',
            field=models.IntegerField(blank=True, help_text='Codigo na tabela do historico', null=True, verbose_name='Codigo na tabela do historico'),
        ),
    ]
