# Generated by Django 2.2.5 on 2019-11-12 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tccStudentRegistration', '0012_auto_20191104_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(help_text='Nome do Usuario cadastrado', max_length=255, verbose_name='Nome')),
                ('email_usuario', models.CharField(help_text='Email do Usuario cadastrado', max_length=255, verbose_name='Email')),
                ('senha_usuario', models.CharField(help_text='Senha do Usuario cadastrado', max_length=255, verbose_name='Senha')),
                ('admin_usuario', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PredicaoEvasao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_predicao', models.DateField(help_text='Período em que o script fez a predicao', verbose_name='Período em que a predicao foi feita')),
                ('script_predicao', models.CharField(help_text='Nome do script de predicao utilizado', max_length=45, verbose_name='Script predicao')),
                ('aluno', models.ForeignKey(help_text='GRR e nome do aluno', on_delete=django.db.models.deletion.CASCADE, to='tccStudentRegistration.Aluno', verbose_name='Nome do aluno')),
                ('forma_evasao', models.ForeignKey(blank=True, help_text='Forma de evasão do aluno do curso', null=True, on_delete=django.db.models.deletion.CASCADE, to='tccStudentRegistration.FormaEvasao', verbose_name='Forma de evasão')),
            ],
        ),
    ]
