# Generated by Django 2.2.5 on 2019-11-12 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tccStudentRegistration', '0013_predicaoevasao_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_comentario', models.CharField(help_text='Conteudo do comentario', max_length=255, verbose_name='Comentario')),
                ('data_comentario', models.DateField(help_text='Período em que o comentario foi postado', verbose_name='Data comentario')),
                ('aluno', models.ForeignKey(help_text='Aluno que fez o comentario', on_delete=django.db.models.deletion.CASCADE, to='tccStudentRegistration.Aluno', verbose_name='Nome do aluno')),
                ('user', models.ForeignKey(help_text='Usuario que fez o comentario', on_delete=django.db.models.deletion.CASCADE, to='tccStudentRegistration.FormaEvasao', verbose_name='Usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
