# Generated by Django 2.2 on 2019-11-12 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tccStudentRegistration', '0014_auto_20191112_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='aluno',
            field=models.ForeignKey(help_text='Aluno que recebeu o comentário do usuário', on_delete=django.db.models.deletion.CASCADE, to='tccStudentRegistration.Aluno', verbose_name='Nome do aluno'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='data_comentario',
            field=models.DateField(help_text='Período em que o comentário foi postado', verbose_name='Data comentário'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto_comentario',
            field=models.CharField(help_text='Conteúdo do comentário', max_length=255, verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formaevasao',
            name='cod_tabela',
            field=models.IntegerField(blank=True, help_text='Código na tabela do histórico', null=True, verbose_name='Código na tabela do histórico'),
        ),
        migrations.AlterField(
            model_name='formaingresso',
            name='cod_tabela',
            field=models.IntegerField(blank=True, help_text='Código na tabela do histórico', null=True, verbose_name='Código na tabela do histórico'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(help_text='Curso em que a matrícula foi feita', on_delete=django.db.models.deletion.CASCADE, to='tccStudentRegistration.Curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='predicaoevasao',
            name='periodo_predicao',
            field=models.DateField(help_text='Período em que o script fez a predição', verbose_name='Período em que a predição foi feita'),
        ),
        migrations.AlterField(
            model_name='predicaoevasao',
            name='script_predicao',
            field=models.CharField(help_text='Nome do script de predição utilizado', max_length=45, verbose_name='Script de predição'),
        ),
        migrations.AlterField(
            model_name='situacaomatricula',
            name='cod_tabela',
            field=models.IntegerField(blank=True, help_text='Código na tabela do histórico', null=True, verbose_name='Código na tabela do histórico'),
        ),
    ]
