nameDisciplinas = ["Teoria da computação",
    "Computabilidade e Modelos de computação",
    "Linguagem formais e Autômatos",
    "Análise de algoritmos e complexidade de computação",
    "Lógicas e semântica de programas",
    "Matemática da computação",
    "Matemática simbólica",
    "Modelos analíticos e de simulação",
    "Metodologia e técnicas da computação",
    "Linguagens de programação",
    "Engenharia de software",
    "Banco de dados",
    "Sistemas de informação",
    "Processamento gráfico",
    "Sistema de computação",
    "Hardware",
    "Arquitetura de sistemas de computação",
    "Software básico",
    "Teleinformática",
    "Álgebra",
    "Conjuntos",
    "Lógica matemática",
    "Teoria dos números",
    "Grupo de Álgebra não comutativa",
    "Álgebra comutativa",
    "Geometria algébrica",
    "Análise",
    "Análise complexa",
    "Análise funcional",
    "Análise Funcional não linear",
    "Equações",
    "Equações diferenciais ordinárias",
    "Equações diferenciais parciais",
    "Equações diferenciais funcionais",
    "Geometria e Topologia",
    "Geometria diferencial",
    "Topologia algébrica",
    "Topologia das variedades",
    "Teoria das singularidades e Teoria das catástrofes",
    "Teoria das folheações",
    "Matemática aplicada",
    "Física matemática",
    "Análise numérica",
    "Matemática discreta e combinatória",
    "Teoria geral e fundamentos da probabilidade",
    "Teoria geral e processos estocásticos",
    "Teoremas de limite",
    "Processos markovianos",
    "Análise estocástica",
    "Processos estocásticos especiais",
    "Estatística",
    "Fundamentos da estatística",
    "Inferência paramétrica",
    "Inferência não paramétrica",
    "Inferência em processos estocásticos",
    "Análise multivariada",
    "Regressão e Correlação",
    "Planejamento de experimentos",
    "Análise de dados",
    "Probabilidade e estatística aplicadas",
    "Física geral",
    "Métodos matemáticos da Física",
    "Física clássica e Física quântica",
    "Mecânica e campos",
    "Relatividade e Gravitação",
    "Física estatística e Termodinâmica",
    "Metrologia técnica geral de laboratório e sistema de instrumentação",
    "Instrumentação específica de uso geral em Física",
    "Áreas clássicas de fenomenologia e suas aplicações",
    "Eletricidade e magnetismo",
    "Ótica",
    "Acústica",
    "Reologia",
    "Dinâmica dos fluidos",
    "Física nuclear",
    "Física das partículas elementares e campos",
    "Teoria geral de partículas e campos",
    "Teoria especial e modo de interação",
    "Sistema de partículas",
    "Raios cósmicos",
    "Reações específicas e fenomiologia de partículas",
    "Propriedades de partículas específicas e ressonâncias",
    "Estrutura química, conformação e Estereoquímica",
    "Síntese orgânica",
    "Físico-química orgânica",
    "Fotoquímica orgânica",
    "Química dos produtos naturais",
    "Evolução, sistemática e ecologia química",
    "Polímeros e Coloides etc",
    "Química inorgânica",
    "Campos de coordenação",
    "Não-metais e seus compostos",
    "Compostos organometálicos",
    "Determinação de estruturas de compostos inorgânicos",
    "Físico química inorgânica",
    "Fotoquímica inorgânica",
    "Química bio-inorgânica",
    "Físico-química",
    "Cinética química e Catálise",
    "Eletroquímica",
    "Espectroscopia",
    "Química de interfaces",
    "Química do estado condensado",
    "Química nuclear e Radioquímica",
    "Química teórica",
    "Termodinâmica química",
    "Química analítica",
    "Separação",
    "Métodos óticos de análise",
    "Eletroanalítica",
    "Gravimetria",
    "Titimetria",
    "Instrumentação analítica",
    "Análise de traços e química ambiental",
    "Geologia",
    "Mineralogia",
    "Petrologia",
    "Geoquímica",
    "Geologia regional",
    "Geotectônica",
    "Geocronologia",
    "Cartografia geológica",
    "Metalogenia",
    "Hidrogeologia",
    "Prospecção mineral",
    "Sedimentologia",
    "Paleontologia estratigráfica",
    "Estratigrafia",
    "Geologia ambiental",
    "Geofísica",
    "Geomagnetismo",
    "Sismologia",
    "Geotermia e fluxo térmico",
    "Propriedades físicas das rochas",
    "Geofísica nuclear",
    "Geotermia",
    "Sensoriamento remoto",
    "Aeronomia",
    "Desenvolvimento de instrumentação geofísica",
    "Geofísica aplicada",
    "Gravimetria",
    "Meteorologia",
    "Meteorologia dinâmica",
    "Meteorologia sinótica",
    "Meteorologia física",
    "Química da atmosfera",
    "Instrumentação meteorológica",
    "Climatologia",
    "Micrometeorologia",
    "Sensoriamento remoto da atmosfera",
    "Meteorologia aplicada",
    "Geodésia",
    "Geodésia física",
    "Geodésia geométrica",
    "Geodésia celeste",
    "Fotogrametria",
    "Cartografia",
    "Geografia física",
    "Geomorfologia",
    "Climatologia geográfica",
    "Pedologia",
    "Hidrogeografia",
    "Geoecologia",
    "Fotogeografia (físico-ecológica)",
    "Geocartografia",
    "Oceanografia física",
    "Variáveis físicas da água do mar",
    "Movimento da água do mar",
    "Origem das massas de água",
    "Interação do oceano com o leito do mar",
    "Interação do oceano com a atmosfera",
    "Oceanografia química",
    "Propriedades químicas da água do mar",
    "Química da água do mar",
    "Oceanografia geológica",
    "Geomorfologia submarina",
    "Sedimentologia marinha",
    "Geofísica marinha",
    "Geoquímica marinha",
    "Genética",
    "Genética quantitativa",
    "Genética molecular e de micro-organismos etc",
    "Mutagênese",
    "Morfologia",
    "Citologia e biologia celular",
    "Embriologia",
    "Histologia",
    "Anatomia",
    "Anatomia humana",
    "Anatomia animal",
    "Fisiologia",
    "Neurofisiologia",
    "Fisiologia renal",
    "Cinesiologia etc",
    "Bioquímica",
    "Bioquímica",
    "Proteínas",
    "Lipídeos",
    "Biologia molecular",
    "Enzimologia etc",
    "Biofísica",
    "Biofísica molecular",
    "Biofísica celular etc",
    "Farmacologia",
    "Farmacocinética",
    "Etnofarmacologia",
    "Toxicologia etc",
    "Imunologia",
    "Imunoquímica",
    "Imunogenética",
    "Microbiologia",
    "Virologia",
    "Bacteriologia",
    "Micologia etc",
    "Parasitologia",
    "Protozooses",
    "Helmintoses",
    "Ectoparasitoses",
    "Ecologia",
    "Ecossistemas",
    "Ecologia aplicada",
    "Oceanografia",
    "Oceanografia biológica",
    "Botânica",
    "Paleobotânica",
    "Morfologia vegetal",
    "Anatomia vegetal",
    "Palinologia",
    "Fisiologia vegetal",
    "Fitogeografia etc",
    "Zoologia",
    "Paleozoologia",
    "Comportamento animal",
    "Taxonomia"]
